version: '3.8'
services:
    web:
        build: 
            context: .
            dockerfile: '/home/hello/Projects/university/Dockerfile'
        command: 'python3 manage.py runserver 0.0.0.0:8000'
        volumes:
            - .:/university
        ports:
            - '8000:8000'
