# Generated by Django 3.1.5 on 2021-01-31 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0002_auto_20210131_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.university'),
        ),
    ]
